deploy_production:
  type: deploy
  environment:
    name: production
    url: leovanhaaren.com
  script:
    - mkdir -p /home/leo/www/leovanhaaren
    - cp -r ./* /home/leo/www/leovanhaaren
  tags:
    - deploy-digital-ocean
  only:
    - master