deploy_staging:
  type: deploy
  environment:
    name: staging
    url: alpacio.com
  script:
    - cp -r ./* /home/leo/nginx-proxy-manager/www/html/leovanhaaren
  tags:
    - deploy-digital-ocean
  only:
    - master