deploy_staging:
  type: deploy
  environment:
    name: staging
    url: alpacio.com
  script:
    - cp -r . /home/leo/node_project/views/alpacio
  tags:
    - deploy-digital-ocean
  only:
    - master